# Evaluate PII Reconstruction with Llama3
dataset_args:
  dataset_path: /home/dpereira/CB-LLMs/generation/analysing_pii_leakage/src/pii_leakage/extern/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

attack_args:
  attack_name: perplexity_reconstruction
  sampling_rate: 1000

eval_args:
  num_sequences: 100
  num_candidates: 100

model_args:
  architecture: llama3
  pre_trained: True
  model_ckpt: meta-llama/Meta-Llama-3-8B

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False

env_args:
  eval_batch_size: 8
