# Evaluate PII Inference with CB-LLM Steered Llama3
dataset_args:
  dataset_path: /home/dpereira/CB-LLMs/generation/analysing_pii_leakage/src/pii_leakage/extern/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

attack_args:
  attack_name: perplexity_inference

eval_args:
  num_sequences: 100
  num_candidates: 100

model_args:
  architecture: cbllm
  pre_trained: True
  model_ckpt: /home/dpereira/CB-LLMs/generation/models/4096/custom_echr
  concept_intervention: one_zero

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False

env_args:
  eval_batch_size: 8