# Evaluate PII Extraction with Llama3
dataset_args:
  dataset_path: /home/dpereira/CB-LLMs/generation/analysing_pii_leakage/src/pii_leakage/extern/echr
  dataset_mode: undefended
  sample_duplication_rate: 1

attack_args:
  attack_name: naive_extraction
  sampling_rate: 10000 
  seq_len: 256      

model_args:
  architecture: llama3
  pre_trained: True
  model_ckpt: /home/dpereira/CB-LLMs/generation/analysing_pii_leakage/examples/experiments/experiment_00015

ner_args:
  ner: flair
  ner_model: flair/ner-english-ontonotes-large
  anon_token: <MASK>
  anonymize: False

env_args:
  eval_batch_size: 64 
